// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parcial2AP1.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 20.0,
                            Descripcion = "Mani Japones",
                            Existencia = 12,
                            Precio = 35.0
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 50.0,
                            Descripcion = "Pistacho",
                            Existencia = 10,
                            Precio = 75.0
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 60.0,
                            Descripcion = "Cajuil salado",
                            Existencia = 5,
                            Precio = 90.0
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 33.0,
                            Descripcion = "Almendras",
                            Existencia = 2,
                            Precio = 50.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
